### PR TITLE
change the config merge/load order

### PR DESCRIPTION
**Pull request by emphasize**
This changes the load/merge order to:
USER > SYSTEM > REMOTE > DEFAULT

### CODE REVIEW

**Comment by JarbasAl** [comment]
see https://github.com/MycroftAI/mycroft-core/pull/2861

not sure how this bug made it over here as it was extensively discussed an unwanted to make remote > system

**Comment by emphasize** [comment]
> not sure how this bug made it over here as it was extensively discussed an unwanted to make remote > system

additionally, the former test masked the problem

**Review by NeonDaniel — APPROVED** [review]
Looks good to me and tested to work under a recent Neon image. Unit test failures are related to a `setuptools` vulnerability and out of scope of this PR

**Review by ChanceNCounter — APPROVED** [review]
Looks right, I remember the original discussion, I concur it’s needed and Daniel has manually tested.

**Pull request merged**
